/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* ── TalentAI Design Tokens (exact from Stitch export) ── */
        background:         '#0b1326',
        surface:            '#0b1326',
        'surface-dim':      '#0b1326',
        'surface-container-lowest': '#060e20',
        'surface-container-low':    '#131b2e',
        'surface-container':        '#171f33',
        'surface-container-high':   '#222a3d',
        'surface-container-highest':'#2d3449',
        'surface-variant':  '#2d3449',
        'surface-bright':   '#31394d',
        'surface-tint':     '#c0c1ff',

        primary:            '#c0c1ff',
        'primary-fixed':    '#e1e0ff',
        'primary-fixed-dim':'#c0c1ff',
        'primary-container':'#8083ff',
        'on-primary':       '#1000a9',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-primary-container':     '#0d0096',
        'inverse-primary':  '#494bd6',

        secondary:          '#4edea3',
        'secondary-fixed':  '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'secondary-container': '#00a572',
        'on-secondary':     '#003824',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'on-secondary-container': '#00311f',

        tertiary:           '#ffb95f',
        'tertiary-fixed':   '#ffddb8',
        'tertiary-fixed-dim':'#ffb95f',
        'tertiary-container':'#ca8100',
        'on-tertiary':      '#472a00',
        'on-tertiary-fixed':'#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary-container':     '#3e2400',

        error:              '#ffb4ab',
        'error-container':  '#93000a',
        'on-error':         '#690005',
        'on-error-container':'#ffdad6',

        'on-surface':        '#dae2fd',
        'on-surface-variant':'#c7c4d7',
        'on-background':     '#dae2fd',

        outline:            '#908fa0',
        'outline-variant':  '#464554',
        'inverse-surface':  '#dae2fd',
        'inverse-on-surface':'#283044',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm':  ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md':  ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md':   ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg':   ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm':['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md':['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      spacing: {
        xs:  '8px',
        sm:  '16px',
        md:  '24px',
        lg:  '32px',
        xl:  '48px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        base: '4px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'pulse-indigo': 'pulseIndigo 2s infinite',
        'spin-slow': 'spin 3s linear infinite',
        'score-ring': 'scoreRing 1s ease-out forwards',
      },
      keyframes: {
        fadeIn: { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideUp: { from: { opacity: 0, transform: 'translateY(20px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        pulseIndigo: {
          '0%':   { boxShadow: '0 0 0 0 rgba(99,102,241,0.4)' },
          '70%':  { boxShadow: '0 0 0 10px rgba(99,102,241,0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(99,102,241,0)' },
        },
        scoreRing: { from: { strokeDashoffset: '125.6' } },
      },
      backdropBlur: { xs: '4px' },
      boxShadow: {
        'glow-primary': '0 0 20px rgba(192,193,255,0.15)',
        'glow-secondary': '0 0 20px rgba(78,222,163,0.15)',
        'active': '0 0 12px rgba(99,102,241,0.2)',
      },
    },
  },
  plugins: [],
}
